#this file is used to build the base Docker image for spfy
# to be tagged as nitzoy/backend-production:latest
FROM superphy/docker-flask-conda:latest

# Add maximum upload of 100 m
COPY upload_60G.conf /etc/nginx/conf.d/

COPY ./app /app
WORKDIR /app

ENV PATH /opt/conda/bin:$PATH

# activate the app environment
ENV PATH /opt/conda/envs/backend/bin:$PATH
#### End Spfy

RUN echo $PATH
RUN which uwsgi

CMD ["/usr/bin/supervisord"]
