#this file is used to build the base Docker image for spfy
# to be tagged as nitzoy/backend-production:latest
FROM superphy/docker-flask-conda:2.0.0

## Nginx:
# Make NGINX run on the foreground
#TEMPORARY RUN echo "daemon off;" >> /etc/nginx/nginx.conf
# Remove default configuration from Nginx
#TEMPORARY RUN rm /etc/nginx/conf.d/default.conf
# Copy the modified Nginx conf
COPY nginx.conf /etc/nginx/conf.d/
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY uwsgi-base.ini /etc/uwsgi/
#TEMPORARY
RUN rm /etc/nginx/conf.d/upload_100m.conf

COPY ./app /app
WORKDIR /app

ENV PATH /opt/conda/bin:$PATH

# activate the app environment
ENV PATH /opt/conda/envs/backend/bin:$PATH
#### End Spfy

RUN echo $PATH
RUN which uwsgi

CMD ["/usr/bin/supervisord"]
