FROM node:7.10.0-alpine

# set yarn version
ENV YARN_VERSION 0.17.6

# Create app directory
RUN mkdir /app

# Install app dependencies & build
COPY ./reactapp /app
WORKDIR /app
RUN yarn install
#debug
RUN ls -lah
RUN yarn build

# Install serve
RUN yarn add serve && \
  yarn serve -s build

EXPOSE 5000

# defined in package.json
CMD [ "yarn", "serve", "-s build" ]
