FROM node:9.2.0

# set yarn version
ENV YARN_VERSION 0.17.6

# Create app directory
RUN mkdir /app

# Install app dependencies & build
COPY ./grouch /app
WORKDIR /app
# part of a bug fix; see https://github.com/sass/node-sass/issues/1579
RUN yarn add node-sass
RUN npm rebuild node-sass

RUN yarn install
#debug
RUN ls -lah
RUN yarn build

WORKDIR build
# Install serve
RUN yarn add serve

EXPOSE 3000

# defined in package.json
CMD [ "yarn", "serve", "--single", "./build" ]
